plugins {
    id 'java'
    id 'application'
}

group = 'edu.pucmm.icc352'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

application {
    mainClass = 'edu.pucmm.icc352.events.bootstrap.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:7.0.1'
    implementation 'org.hibernate.orm:hibernate-core:6.6.18.Final'
    implementation 'org.flywaydb:flyway-core:11.13.3'
    implementation 'com.h2database:h2:2.4.240'
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'com.google.zxing:core:3.5.4'
    implementation 'com.google.zxing:javase:3.5.4'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.20.0'
    implementation 'ch.qos.logback:logback-classic:1.5.20'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}
