create table users (
    id bigint generated by default as identity primary key,
    username varchar(50) not null,
    full_name varchar(120) not null,
    email varchar(120) not null,
    password_hash varchar(255) not null,
    active boolean not null,
    immutable_admin boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_users_username unique (username),
    constraint uk_users_email unique (email)
);

create table user_roles (
    user_id bigint not null,
    role varchar(30) not null,
    primary key (user_id, role),
    constraint fk_user_roles_user foreign key (user_id) references users (id) on delete cascade
);

create table events (
    id bigint generated by default as identity primary key,
    title varchar(150) not null,
    description clob not null,
    starts_at timestamp not null,
    location varchar(150) not null,
    max_capacity integer not null,
    status varchar(30) not null,
    created_by_user_id bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    cancelled_at timestamp null,
    constraint fk_events_created_by foreign key (created_by_user_id) references users (id)
);

create index idx_events_status_starts_at on events (status, starts_at);

create table registrations (
    id bigint generated by default as identity primary key,
    event_id bigint not null,
    user_id bigint not null,
    validation_token varchar(120) not null,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    cancelled_at timestamp null,
    attendance_marked_at timestamp null,
    constraint fk_registrations_event foreign key (event_id) references events (id) on delete cascade,
    constraint fk_registrations_user foreign key (user_id) references users (id),
    constraint uk_registrations_event_user unique (event_id, user_id),
    constraint uk_registrations_validation_token unique (validation_token)
);

create index idx_registrations_event_status on registrations (event_id, status);
create index idx_registrations_token on registrations (validation_token);
